apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-project-database-backend
  description: "ip:10.11.201.55:1525"
spec:
  type: database
  owner: user:default/guest
  system: test-system
  
